### PR TITLE
Fix failing ci run

### PR DESCRIPTION
**Pull request by mgrover1**
This attempts to fix the failing CI.

One issue we will run into here is the "requester pays" nature of the example dataset, which is referenced in this intake catalog

https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/ocean/CESM_POP.yaml

We will need to configure a google cloud with an associated credit card and store in the credentials.

### CODE REVIEW

**Comment by cmdupuis3** [comment]
Thanks for having a look at this. Apparently I left some old copies of the notebooks lying around in the wrong directories, so the original paths were correct.

**Comment by cmdupuis3** [comment]
Manually merged with cherry-pick

**Comment by cmdupuis3** [comment]
I expect that this isn't actually the full solution, so feel free to reopen the PR on a new branch.

**Comment by cmdupuis3** [comment]
@ktyle @mgrover1 I hadn't considered that the requester-pays model could be an issue, but I think the source file is actually pretty large. We could definitely make do with a much smaller subset, but due to autoregression, the snapshots we choose would have to be widely separated in time.

**Comment by rabernat** [comment]
> I'm not sure if a requester-pays model on a Binderhub is going to be viable

For context, in Pangeo Gallery we solved this issue by running the binderhub in the same cloud region as the data, thereby bypassing the need to actually pay for requester pays (although the credentials still had to be configured). This is really important for cloud-native workflows on real datasets.

Can you explain where (in which cloud / cloud region) the notebooks are executing in this CI workflow?

**Comment by mgrover1** [comment]
These notebooks are executing on jetstream-2

**Pull request closed without merging**
